# Build configuration for C++ with CMake and Eigen on Ubuntu 16.04.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: gcc:6.1
image: 
  name: graalunige/xenial-testbench
  username: $DOCKER_HUB_USERNAME_WANDERFRA
  password: $DOCKER_HUB_PASSWORD_WANDERFRA
  email: $DOCKER_HUB_EMAIL_WANDERFRA

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # install deps
          #  - apt-get update
          #  - apt-get install -y cmake libeigen3-dev
          #build
            - cmake .
            - make